name: huamn_pp
task_type: single_dataset
task_modes: []

shape_meta:
  image_resolution: 96
  action:
    shape:
    - 14
  obs:
    agent_pos:
      shape:
      - 14
      type: low_dim
    image:
      shape:
      - 3
      - 96
      - 96
      type: rgb

dataset:
  _target_: unified_video_action.dataset.human_image_dataset.HumanImageDataset
  language_emb_model: null
  horizon: 32
  pad_after: 7
  pad_before: 1
  seed: 42
  val_ratio: 0.02
  data_aug: true
  normalizer_type: all
  dataset_path: data/human_pp/pp_in_with_keypoints.zarr
  dataset_type: singletask

keypoints:
  eval: true
# env_runner:
#   _target_: unified_video_action.env_runner.pusht_image_runner.PushTImageRunner
#   fps: 10
#   legacy_test: true
#   max_steps: 300
#   n_action_steps: 8
#   n_envs: null
#   n_obs_steps: 16
#   n_test: 50
#   n_test_vis: 4
#   n_train: 6
#   n_train_vis: 2
#   past_action: false
#   test_start_seed: 100000
#   train_start_seed: 0
#   fix_goal: true
